server:
  port: 9001



spring:
  application:
    name: study-dubbo-product
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848


dubbo:
  scan:
    base-packages: com.lincheng.study.dubbo.service.impl
  application:
    name: ${spring.application.name}
  monitor:
    protocol: registry
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20881


