server:
  port: 8081

spring:
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名
    username: 2826117968@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码(在邮箱中设置)
    password: gvkpgdixvuiudfhf
