server:
  port: 9002

spring:
  application:
    name: study-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20880
  cloud:
    #订阅提供者的服务
    subscribed-services: study-dubbo-product
